/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesBrandingRouteImport } from './routes/services.branding'
import { Route as ServicesGraphicDesignRouteImport } from './routes/services.graphic-design'
import { Route as ServicesSocialMediaDesignRouteImport } from './routes/services.social-media-design'
import { Route as ServicesWebsiteDesignRouteImport } from './routes/services.website-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/services/branding',
  path: '/services/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGraphicDesignRoute = ServicesGraphicDesignRouteImport.update({
  id: '/services/graphic-design',
  path: '/services/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSocialMediaDesignRoute =
  ServicesSocialMediaDesignRouteImport.update({
    id: '/services/social-media-design',
    path: '/services/social-media-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesWebsiteDesignRoute = ServicesWebsiteDesignRouteImport.update({
  id: '/services/website-design',
  path: '/services/website-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/branding'
    | '/services/graphic-design'
    | '/services/social-media-design'
    | '/services/website-design'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/branding'
    | '/services/graphic-design'
    | '/services/social-media-design'
    | '/services/website-design'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/branding'
    | '/services/graphic-design'
    | '/services/social-media-design'
    | '/services/website-design'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesGraphicDesignRoute: typeof ServicesGraphicDesignRoute
  ServicesSocialMediaDesignRoute: typeof ServicesSocialMediaDesignRoute
  ServicesWebsiteDesignRoute: typeof ServicesWebsiteDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/services/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/graphic-design': {
      id: '/services/graphic-design'
      path: '/services/graphic-design'
      fullPath: '/services/graphic-design'
      preLoaderRoute: typeof ServicesGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-design': {
      id: '/services/social-media-design'
      path: '/services/social-media-design'
      fullPath: '/services/social-media-design'
      preLoaderRoute: typeof ServicesSocialMediaDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-design': {
      id: '/services/website-design'
      path: '/services/website-design'
      fullPath: '/services/website-design'
      preLoaderRoute: typeof ServicesWebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesGraphicDesignRoute: ServicesGraphicDesignRoute,
  ServicesSocialMediaDesignRoute: ServicesSocialMediaDesignRoute,
  ServicesWebsiteDesignRoute: ServicesWebsiteDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
