/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServicesAndMoreRouteImport } from './routes/services.and-more'
import { Route as ServicesBrandingRouteImport } from './routes/services.branding'
import { Route as ServicesBrochureDesignRouteImport } from './routes/services.brochure-design'
import { Route as ServicesBusinessCardDesignRouteImport } from './routes/services.business-card-design'
import { Route as ServicesFlyerDesignRouteImport } from './routes/services.flyer-design'
import { Route as ServicesGraphicDesignRouteImport } from './routes/services.graphic-design'
import { Route as ServicesPackagingDesignRouteImport } from './routes/services.packaging-design'
import { Route as ServicesPosterDesignRouteImport } from './routes/services.poster-design'
import { Route as ServicesPresentationDesignRouteImport } from './routes/services.presentation-design'
import { Route as ServicesSocialMediaDesignRouteImport } from './routes/services.social-media-design'
import { Route as ServicesThumbnailDesignRouteImport } from './routes/services.thumbnail-design'
import { Route as ServicesVideoEditingRouteImport } from './routes/services.video-editing'
import { Route as ServicesWebsiteDesignRouteImport } from './routes/services.website-design'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesAndMoreRoute = ServicesAndMoreRouteImport.update({
  id: '/services/and-more',
  path: '/services/and-more',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrandingRoute = ServicesBrandingRouteImport.update({
  id: '/services/branding',
  path: '/services/branding',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBrochureDesignRoute = ServicesBrochureDesignRouteImport.update({
  id: '/services/brochure-design',
  path: '/services/brochure-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesBusinessCardDesignRoute =
  ServicesBusinessCardDesignRouteImport.update({
    id: '/services/business-card-design',
    path: '/services/business-card-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesFlyerDesignRoute = ServicesFlyerDesignRouteImport.update({
  id: '/services/flyer-design',
  path: '/services/flyer-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesGraphicDesignRoute = ServicesGraphicDesignRouteImport.update({
  id: '/services/graphic-design',
  path: '/services/graphic-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPackagingDesignRoute = ServicesPackagingDesignRouteImport.update({
  id: '/services/packaging-design',
  path: '/services/packaging-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPosterDesignRoute = ServicesPosterDesignRouteImport.update({
  id: '/services/poster-design',
  path: '/services/poster-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesPresentationDesignRoute =
  ServicesPresentationDesignRouteImport.update({
    id: '/services/presentation-design',
    path: '/services/presentation-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSocialMediaDesignRoute =
  ServicesSocialMediaDesignRouteImport.update({
    id: '/services/social-media-design',
    path: '/services/social-media-design',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesThumbnailDesignRoute = ServicesThumbnailDesignRouteImport.update({
  id: '/services/thumbnail-design',
  path: '/services/thumbnail-design',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesVideoEditingRoute = ServicesVideoEditingRouteImport.update({
  id: '/services/video-editing',
  path: '/services/video-editing',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebsiteDesignRoute = ServicesWebsiteDesignRouteImport.update({
  id: '/services/website-design',
  path: '/services/website-design',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/and-more': typeof ServicesAndMoreRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/brochure-design': typeof ServicesBrochureDesignRoute
  '/services/business-card-design': typeof ServicesBusinessCardDesignRoute
  '/services/flyer-design': typeof ServicesFlyerDesignRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/packaging-design': typeof ServicesPackagingDesignRoute
  '/services/poster-design': typeof ServicesPosterDesignRoute
  '/services/presentation-design': typeof ServicesPresentationDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/thumbnail-design': typeof ServicesThumbnailDesignRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/and-more': typeof ServicesAndMoreRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/brochure-design': typeof ServicesBrochureDesignRoute
  '/services/business-card-design': typeof ServicesBusinessCardDesignRoute
  '/services/flyer-design': typeof ServicesFlyerDesignRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/packaging-design': typeof ServicesPackagingDesignRoute
  '/services/poster-design': typeof ServicesPosterDesignRoute
  '/services/presentation-design': typeof ServicesPresentationDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/thumbnail-design': typeof ServicesThumbnailDesignRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/services/and-more': typeof ServicesAndMoreRoute
  '/services/branding': typeof ServicesBrandingRoute
  '/services/brochure-design': typeof ServicesBrochureDesignRoute
  '/services/business-card-design': typeof ServicesBusinessCardDesignRoute
  '/services/flyer-design': typeof ServicesFlyerDesignRoute
  '/services/graphic-design': typeof ServicesGraphicDesignRoute
  '/services/packaging-design': typeof ServicesPackagingDesignRoute
  '/services/poster-design': typeof ServicesPosterDesignRoute
  '/services/presentation-design': typeof ServicesPresentationDesignRoute
  '/services/social-media-design': typeof ServicesSocialMediaDesignRoute
  '/services/thumbnail-design': typeof ServicesThumbnailDesignRoute
  '/services/video-editing': typeof ServicesVideoEditingRoute
  '/services/website-design': typeof ServicesWebsiteDesignRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/and-more'
    | '/services/branding'
    | '/services/brochure-design'
    | '/services/business-card-design'
    | '/services/flyer-design'
    | '/services/graphic-design'
    | '/services/packaging-design'
    | '/services/poster-design'
    | '/services/presentation-design'
    | '/services/social-media-design'
    | '/services/thumbnail-design'
    | '/services/video-editing'
    | '/services/website-design'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/and-more'
    | '/services/branding'
    | '/services/brochure-design'
    | '/services/business-card-design'
    | '/services/flyer-design'
    | '/services/graphic-design'
    | '/services/packaging-design'
    | '/services/poster-design'
    | '/services/presentation-design'
    | '/services/social-media-design'
    | '/services/thumbnail-design'
    | '/services/video-editing'
    | '/services/website-design'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/portfolio'
    | '/services/and-more'
    | '/services/branding'
    | '/services/brochure-design'
    | '/services/business-card-design'
    | '/services/flyer-design'
    | '/services/graphic-design'
    | '/services/packaging-design'
    | '/services/poster-design'
    | '/services/presentation-design'
    | '/services/social-media-design'
    | '/services/thumbnail-design'
    | '/services/video-editing'
    | '/services/website-design'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  ServicesAndMoreRoute: typeof ServicesAndMoreRoute
  ServicesBrandingRoute: typeof ServicesBrandingRoute
  ServicesBrochureDesignRoute: typeof ServicesBrochureDesignRoute
  ServicesBusinessCardDesignRoute: typeof ServicesBusinessCardDesignRoute
  ServicesFlyerDesignRoute: typeof ServicesFlyerDesignRoute
  ServicesGraphicDesignRoute: typeof ServicesGraphicDesignRoute
  ServicesPackagingDesignRoute: typeof ServicesPackagingDesignRoute
  ServicesPosterDesignRoute: typeof ServicesPosterDesignRoute
  ServicesPresentationDesignRoute: typeof ServicesPresentationDesignRoute
  ServicesSocialMediaDesignRoute: typeof ServicesSocialMediaDesignRoute
  ServicesThumbnailDesignRoute: typeof ServicesThumbnailDesignRoute
  ServicesVideoEditingRoute: typeof ServicesVideoEditingRoute
  ServicesWebsiteDesignRoute: typeof ServicesWebsiteDesignRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/and-more': {
      id: '/services/and-more'
      path: '/services/and-more'
      fullPath: '/services/and-more'
      preLoaderRoute: typeof ServicesAndMoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/branding': {
      id: '/services/branding'
      path: '/services/branding'
      fullPath: '/services/branding'
      preLoaderRoute: typeof ServicesBrandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/brochure-design': {
      id: '/services/brochure-design'
      path: '/services/brochure-design'
      fullPath: '/services/brochure-design'
      preLoaderRoute: typeof ServicesBrochureDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/business-card-design': {
      id: '/services/business-card-design'
      path: '/services/business-card-design'
      fullPath: '/services/business-card-design'
      preLoaderRoute: typeof ServicesBusinessCardDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/flyer-design': {
      id: '/services/flyer-design'
      path: '/services/flyer-design'
      fullPath: '/services/flyer-design'
      preLoaderRoute: typeof ServicesFlyerDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/graphic-design': {
      id: '/services/graphic-design'
      path: '/services/graphic-design'
      fullPath: '/services/graphic-design'
      preLoaderRoute: typeof ServicesGraphicDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/packaging-design': {
      id: '/services/packaging-design'
      path: '/services/packaging-design'
      fullPath: '/services/packaging-design'
      preLoaderRoute: typeof ServicesPackagingDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/poster-design': {
      id: '/services/poster-design'
      path: '/services/poster-design'
      fullPath: '/services/poster-design'
      preLoaderRoute: typeof ServicesPosterDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/presentation-design': {
      id: '/services/presentation-design'
      path: '/services/presentation-design'
      fullPath: '/services/presentation-design'
      preLoaderRoute: typeof ServicesPresentationDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/social-media-design': {
      id: '/services/social-media-design'
      path: '/services/social-media-design'
      fullPath: '/services/social-media-design'
      preLoaderRoute: typeof ServicesSocialMediaDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/thumbnail-design': {
      id: '/services/thumbnail-design'
      path: '/services/thumbnail-design'
      fullPath: '/services/thumbnail-design'
      preLoaderRoute: typeof ServicesThumbnailDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/video-editing': {
      id: '/services/video-editing'
      path: '/services/video-editing'
      fullPath: '/services/video-editing'
      preLoaderRoute: typeof ServicesVideoEditingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/website-design': {
      id: '/services/website-design'
      path: '/services/website-design'
      fullPath: '/services/website-design'
      preLoaderRoute: typeof ServicesWebsiteDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  ServicesAndMoreRoute: ServicesAndMoreRoute,
  ServicesBrandingRoute: ServicesBrandingRoute,
  ServicesBrochureDesignRoute: ServicesBrochureDesignRoute,
  ServicesBusinessCardDesignRoute: ServicesBusinessCardDesignRoute,
  ServicesFlyerDesignRoute: ServicesFlyerDesignRoute,
  ServicesGraphicDesignRoute: ServicesGraphicDesignRoute,
  ServicesPackagingDesignRoute: ServicesPackagingDesignRoute,
  ServicesPosterDesignRoute: ServicesPosterDesignRoute,
  ServicesPresentationDesignRoute: ServicesPresentationDesignRoute,
  ServicesSocialMediaDesignRoute: ServicesSocialMediaDesignRoute,
  ServicesThumbnailDesignRoute: ServicesThumbnailDesignRoute,
  ServicesVideoEditingRoute: ServicesVideoEditingRoute,
  ServicesWebsiteDesignRoute: ServicesWebsiteDesignRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
